paths:
  /signup:
    post:
      summary: Register a user
      tags:
        - Index
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad Request - Invalid or Missing Parameters
          content:
            application/json:
              example:
                - email_missing: true
                  message: 'Error: User email is not specified'
                - password_missing: true
                  message: 'Error: User password is not specified'
                - user_exists: true
                  message: 'Error: User already exists in sign up'
        '500':
          description: Internal Server Error - Unexpected error occurred on the server
          content:
            application/json:
              example:
                - user_create_failed: true
                  message: 'Error: Could not create user in sign up'
                - user_fetch_failed: true
                  message: 'Error: Could not fetch user in sign up'

  /login:
    get:
      summary: Login
      tags: 
        - Index
      parameters:
        - in: header
          name: email
          schema:
            type: string
            format: email
          required: true
        - in: header
          name: password
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad Request - Invalid or Missing Parameters
          content:
            application/json:
              example:
                - email_missing: true
                  message: 'Error: User email is not specified'
                - password_missing: true
                  message: 'Error: User email is not specified'
                - not_found: true
                  message: 'Error: User does not exist'
                - user_exists: true
                  message: 'Error: Invalid credentials'
        '500':
          description: Internal Server Error - Unexpected error occurred on the server
          content:
            application/json:
              example:
                - user_token_fetch_failed: true
                  message: 'Error: Failed to fetch user token in GET logout'
                - user_token_create_failed: true
                  message: 'Error: Failed to create user token in GET logout'
                - user_exists: true
                  message: 'Error: Failed to verify password in login'
                - user_fetch_failed: true
                  message: 'Error: Failed to fetch user profile in login'
  
  /access_token:
    get:
      summary: Get access and refresh token
      tags: 
        - Index
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                example:
                  message: 'Access and refresh token granted successfully!'
                  access_token: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9'
                  refresh_token: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9'
        '400':
          description: Bad Request - Invalid or Missing Parameters
          content:
            application/json:
              example:
                not_found: true
                message: 'Error: Refresh token cookie not found'
        '403':
          description: Forbidden Request - Unauthorized Access
          content:
            application/json:
              example:
                success: false
                anyOf:
                  - message: 'Error: Failed to authenticate refresh token in GET access token'
                  - message: 'Error: This user does not have permission to get access token'
                  - message: 'Error: Failed to authenticate refresh token in GET access token'
                  - message: 'Error: User ID and refresh token mismatch in GET access token'
        '500':
          description: Internal Server Error - Unexpected error occurred on the server
          content:
            application/json:
              example:
                - user_token_delete_failed: true
                  message: 'Failed to delete user token in GET access token'
                - user_token_create_failed: true
                  message: 'Error: Failed to create user token in GET access token'
                - user_token_fetch_failed: true
                  message: 'Error: Failed to fetch user token in GET access token'
      
  /logout:
    get:
      summary: Logout
      tags: 
        - Index
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'User signed out successfully!'
        '400':
          description: Bad Request - Invalid or Missing Parameters
          content:
            application/json:
              example:
                not_found: true
                message: 'Error: Refresh token cookie not found'
        '500':
          description: Internal Server Error - Unexpected error occurred on the server
          content:
            application/json:
              example:
                - user_token_delete_failed: true
                  message: 'Error: Failed to delete user token in GET logout'
                - user_token_fetch_failed: true
                  message: 'Error: Failed to fetch user token in GET logout'