paths:
  /signup:
    post:
      summary: Register a user
      tags:
        - Index
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /login:
    get:
      summary: Login
      tags: 
        - Index
      parameters:
        - in: header
          name: email
          schema:
            type: string
            format: email
          required: true
        - in: header
          name: password
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  
  /access_token:
    get:
      summary: Get access and refresh token
      tags: 
        - Index
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                example:
                  message: 'Access and refresh token granted successfully!'
                  access_token: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9'
                  refresh_token: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9'
                   
  /logout:
    get:
      summary: Logout
      tags: 
        - Index
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: 'User signed out successfully!'